resource_group_name   = "rg-prod-in-cmu" # these are still hardcoded here, perhaps could use tfvars file 
storage_account_name  = "devsynapsesamcwpbv"
container_name        = "opentofu-state"
key                   = "dev/terraform.tfstate"
#use_azuread_auth      = true